# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Juhyeon Kim
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Juhyeon's web page!
baseurl: #"/bay" # the subpath of the site
url: "https://juhyeon-kim-git.github.io/Juhyeon_Kim.github.io/" # the base hostname & protocol for the site
og_image: ./assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: / # <-- index.md
    #- name: Blog # <-- blog.md
    #- name: Whatever123 # <-- whatever.md

footer:
  show_powered_by: False
  contact:
    - name: Email
      value: kimjh9474@snu.ac.kr
      link: mailto:kimjh9474@snu.ac.kr
    - name: Email
      value: 1 Gwanak-ro (bldg# 942, 3rd fl.), Gwanak-gu, Seoul, 08826, South Korea
  follow:
    - name: Twitter
      link: https://twitter.com/Ju_Hyeon__Kim
      username: "@Juhyeon Kim"
#     - name: Facebook
#       link: http://facebook.com/im.yesong/
    - name: LinkedIn
      link: https://www.linkedin.com/in/juhyeon-kim-101227264/
#    - name: GitHub
#      link: https://github.com/lovelyesong
    #- name: Dribbble
    #  link: https://dribbble.com/YourDribbbleUsername
    #- name: RSS
    #  link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
